import { IColumn } from '../../src/interfaces';
import { generateInterface } from '../../src/generates';

describe('Generate interface', () => {
  it('Should generate the correct TypeScript interface for given columns"', () => {
    const columns: IColumn[]  = [
      {
        name: 'id',
        required: true,
        type: 'number',
        autoGenerated: true,
      },
      {
        name: 'name',
        required: true,
        type: 'string',
        autoGenerated: true,
      },
      {
        name: 'age',
        required: false,
        type: 'date',
      },
      {
        name: 'inactive',
        required: true,
        type: 'boolean'
      },
      {
        name: 'company_id',
        required: false,
        type: 'uuid'
      }
    ];

    const result = generateInterface(columns, 'User');

    const expected = 'export interface User {\nid: number;\nname: string;\nage: Date | null;\ninactive: boolean;\ncompany_id: string | null;\n}'

    expect(result).toStrictEqual(expected);
  });

  it('Should generate the correct TypeScript interface for empty columns', () => {
    const columns: IColumn[]  = [];

    const result = generateInterface(columns, 'User');

    const expected = 'export interface User {\n\n}'

    expect(result).toStrictEqual(expected);
  });
})
