export interface IColumn {
  name: string;
  type:
    'string' |
    'number' |
    'date' |
    'uuid' |
    'boolean';
  required: boolean;
  autoGenerated?: boolean;
  min?: number;
  max?: number;
  defaultValue?: string | number | boolean | null;
}
