import { IType } from './IType';

export interface IColumn {
  name: string;
  type: IType;
  required: boolean;
  autoGenerated?: boolean;
  min?: number;
  max?: number;
  defaultValue?: string | number | boolean | null;
}
