import { IColumn } from 'interfaces';
import { generateClass } from 'generates/generate-class';

import fs from 'node:fs/promises';
import { generateInterface } from 'generates';

const columns: IColumn[]  = [
  {
    name: 'id',
    required: true,
    type: 'number',
    autoGenerated: true,
  },
  {
    name: 'name',
    required: true,
    type: 'string',
    autoGenerated: true,
  },
  {
    name: 'age',
    required: false,
    type: 'date',
  },
  {
    name: 'inactive',
    required: true,
    type: 'boolean'
  },
  {
    name: 'company_id',
    required: false,
    type: 'uuid'
  }
];

const generateIn = generateInterface(columns, 'IUser');
const classg = generateClass('User', 'IUser', columns);

fs.writeFile('output/User.ts', classg)
fs.writeFile('output/IUser.ts', generateIn)
